### ISSUE TITLE
apply failed with conflict

### ISSUE THREAD

**Issue by qingwusunny** [kvaps/helm-ensurecrds#2]
error: Apply failed with 1 conflict: conflict with "helm" using apiextensions.k8s.io/v1: .spec.versions
Please review the fields above--they currently have other managers. Here
are the ways you can resolve this warning:
* If you intend to manage all of these fields, please re-run the apply
  command with the `--force-conflicts` flag.
* If you do not intend to manage all of the fields, please edit your
  manifest to remove references to the fields that should keep their
  current managers.
* You may co-own fields by updating your manifest to match the existing
  value; in this case, you'll become the manager if the other manager(s)
  stop managing the field (remove it from their configuration).
  

but helm ensurecrds -f ecp-values.yaml -n sks-system-ecp --wait ecp-cni ./ecp-cni --set=installCRDs=true --force-conflicts
Error: unknown flag: --force-conflicts

how to resolve it

**Comment by kvaps** [comment]
Hi @qingwusunny could you please check this PR https://github.com/kvaps/helm-ensurecrds/pull/3 if it is solves your problem
